### ISSUE TITLE
Git Commands List

### ISSUE THREAD

**Issue by msamuelpf** [msamuelpf/gen3#3]
## Overview:
In order to develop a document to use for new SW guys you could collaborate with a list of git commands.

## Definition of Done:

- [x] create a summary of concepts like: commit, repository branch, etc...
- [x] create a List with all the commands that you used in the basic training and explain each command.
- [x] add the file in this repo with the name gitForMabeDummies.docx
- [x] add the file in this repo with the name gitForMabeDummies.pdf

**Comment by msamuelpf** [comment]
@FernandaBerthely 
@ldcortez 
@FImorag 

any doubt or comment please do not hesitate to tell me by this way!

**Comment by ldcortez** [comment]
thanks

**Comment by ldcortez** [comment]
the summary of concepts and commands go together?

**Comment by FernandaBerthely** [comment]
> the summary of concepts and commands go together?

i understood that both had to be in the same file

**Comment by ldcortez** [comment]
it makes sense to be only one file, I got confused for a moment ':D, but thanks fer

**Comment by FImorag** [comment]
Is this issue only 2 files by all team or 2 files by each one?

**Comment by ldcortez** [comment]
> Is this issue only 2 files by all team or 2 files by each one?

2 files by each one

**Comment by FImorag** [comment]
I have a problem. Every change that I am doing in my branch automatically appears in dev branch

**Comment by ldcortez** [comment]
[gitForMabeDummies.docx](https://github.com/msamuelpf/gen3/files/6843376/gitForMabeDummies.docx)
[gitForMabeDummies.pdf](https://github.com/msamuelpf/gen3/files/6843377/gitForMabeDummies.pdf)
